### PR TITLE
Add content to ask page

### PR DESCRIPTION
**Pull request by sfbennett**
Have added initial content and styling to the Ask page.

**Desktop:** 
Screenshot 2024-05-21 at 16 11 22

**Mobile:** 
Screenshot 2024-05-21 at 16 11 33

### CODE REVIEW

**Review by cnrdgrgry — APPROVED** [review]
A somewhat tidier solution than mine! I'm a gonna have to 'borrow'!

**Review by hedgehog125 — CHANGES_REQUESTED** [review]
Looks nice. For some reason it doesn't have the overlap on my monitor though?

image

It's behaving similarly when I emulate a 1080p monitor with a pixel ratio of 1.
image

**Comment by hedgehog125** [comment]
Mobile still works fine though

**Review by hedgehog125 — APPROVED** [review]
Backlog item

**Comment by hedgehog125** [comment]
I think this might depend on a proper fix for the header anyway

**Pull request merged**
