### PR TITLE
Add styling to the products page

### PR DESCRIPTION
**Pull request by sfbennett**
Pete has already checked this over and approved -- so this is all ready to be approved and merged straight in. 

Desktop: 
Screenshot 2024-05-24 at 12 05 32

Mobile: 
Screenshot 2024-05-24 at 12 05 47

### CODE REVIEW

**Review by cnrdgrgry — APPROVED** [review]
Getting there .. much improved from before

**Review by hedgehog125 — APPROVED** [review]
Sorry for the delay. That looks like a good start. I assume it also looks like this on yours:

image

Couple of pointers if you want to tweak the JavaScript:

- You can change the display text for each sort mode in Shop.jsx by changing the second item of each of the arrays in SORT_MODES
- You can tweak the number of products per page by changing PRODUCTS_PER_PAGE in ProductResults.jsx

**Comment by cnrdgrgry** [comment]
@hedgehog125 did you read the initial comment - it's a work in progress, doesn't require heavy checking yet. just trying to Get. Stuff. Up and looking slightly bettere with minimal time left.

**Comment by cnrdgrgry** [comment]
Badabing! badaboom!

**Review by cnrdgrgry — APPROVED** [review]

**Pull request merged**
