### PR TITLE
Cg footer improve style

### PR DESCRIPTION
**Pull request by cnrdgrgry**
Improved position of content to match brief more closely (brought the legal and license stuff more 'inboard'

inactive styling is now more discreet
hover is the key color purple with underline

[Screencast from 2024-05-24 11-29-22.webm](https://github.com/technative-academy/PetSynth/assets/143351775/e7741d0b-eb60-4336-af17-ebb93ea516ef)
Screenshot from 2024-05-24 11-29-08

### CODE REVIEW

**Review by hedgehog125 — CHANGES_REQUESTED** [review]
Yeah, that seems better. Can I try and make the width a media query though? I don't think it should apply on mobile.

image

**Comment by cnrdgrgry** [comment]
I believe it's because I've left your @media at 600 while most others are 768

**Comment by cnrdgrgry** [comment]
remember @hedgehog125 it's not unreasonable to just ignore a few key break points, there are so many screen sizes now we just need to get 'good enough' in a few widths that we're actually going to present:

maybe just flex-column?

**Comment by cnrdgrgry** [comment]
and that mobile is 'could', not 'should'

**Comment by hedgehog125** [comment]
Sorry, I should have clarified that a bit more. I meant it should be 100% rather than 70% width once the screen gets small enough

**Comment by cnrdgrgry** [comment]
@hedgehog125 I've edited to 90% - met you in the middle

**Comment by hedgehog125** [comment]
@cnrdgrgry Yeah, that probably makes more sense. I should have also said it should be 100% with a margin, but this is the same thing.

**Review by hedgehog125 — APPROVED** [review]
It's looking good now. Thanks for making those changes

**Review by sfbennett — APPROVED** [review]

**Pull request merged**
